### ISSUE TITLE
what is the license of this project?

### ISSUE THREAD

**Issue by angelga** [jterrace/pyssim#14]
I would love to know if this is open source. Thanks.

**Comment by jterrace** [comment]
Unfortunately, the original version of this source has no license:
http://isit.u-clermont1.fr/~anvacava/code.html

So I don't think I have the ability to attach an explicit license.

**Comment by gi11es** [comment]
At my request, the original author, Antoine Vacavant, picked a license (MIT) and added it to his code: http://isit.u-clermont1.fr/~anvacava/code-ssim-source.html

It would be great if you can define a license for pyssim now.

**Comment by jterrace** [comment]
Thank you!

**Comment by gi11es** [comment]
FYI, it made this possible: https://packages.debian.org/source/sid/pyssim Soon to make it all the way to jessie-backports.

**Comment by jterrace** [comment]
Nice!
