### ISSUE TITLE
SSIM value < 0?

### ISSUE THREAD

**Issue by shanemcquillan** [jterrace/pyssim#15]
Hi. I'm getting a value of -0.01473043 for the two images attached. Any idea what's going on?
![image-magick3_golden](https://cloud.githubusercontent.com/assets/1151334/13691365/2049779a-e6ed-11e5-9ce7-a90463a782af.jpg)
![image-magick3_subject](https://cloud.githubusercontent.com/assets/1151334/13691366/20662aca-e6ed-11e5-872b-aecf2f5027b5.png)

**Comment by jterrace** [comment]
Might be related to #9 - maybe a rounding error?

**Comment by jterrace** [comment]
I was able to reproduce:

````
$ ./venv/bin/pyssim ~/Downloads/20662aca-e6ed-11e5-872b-aecf2f5027b5.png ~/Downloads/2049779a-e6ed-11e5-9ce7-a90463a782af.jpg 
-0.01473043
````

**Comment by jterrace** [comment]
Setting sigma to 0.5 instead of 1.5 comes out as 0.0769464

**Comment by shanemcquillan** [comment]
What is the purpose of the sigma value? Are there any downsides to using 0.5 for all comparisons?

**Comment by shanemcquillan** [comment]
Bumping this again. Can you provide any more info? Why did you choose 1.5 as the default value? Should it perhaps be 0.5 instead? Thanks!

**Comment by jterrace** [comment]
These are the values being used:
        gaussian_kernel_sigma = 1.5
        gaussian_kernel_width = 11

Here's a calculator to show you:
http://dev.theomader.com/gaussian-kernel-calculator/

You can read up on the gaussian kernel here:
http://www.stat.wisc.edu/~mchung/teaching/MIA/reading/diffusion.gaussian.kernel.pdf.pdf

We should at least add it as a command-line argument. But if I understand correctly, the algorithm shouldn't ever produce values outside of 0 to 1. So something must not be clamping correctly.

**Comment by w-m** [comment]
Although unintuitive, values below 0 are in fact correct. The SSIM publications point out the unique maximum at 1 and skip over the part of a minimum value, so many people seem to just assume 0 (me included). It is only mentioned that the third term / the cross correlation can be negative. 

[Structural Approaches to Image Quality Assessment] (https://ece.uwaterloo.ca/~z70wang/publications/HIVP_chapter83.pdf) goes into most detail about this:

> Notice that s(x, y) can take on negative values. As will be shown in later examples, the negative structural similarity values correspond to the cases that the local image structures are inverted.

[Wikipedia](https://en.wikipedia.org/wiki/Structural_similarity) mentions the bounds correctly (-1 to 1), this [OpenCV example](http://docs.opencv.org/2.4/doc/tutorials/gpu/gpu-basics-similarity/gpu-basics-similarity.html) does not (zero to one).

It's easy to reproduce an ssim value close to -1:

```
from numpy.random import randint
from PIL import Image
random_img = randint(0, 255, (1000, 1000)).astype(np.uint8)
print(compute_ssim(Image.fromarray(random_img), Image.fromarray(255 - random_img)))
# -0.965838768437 for me
```

Maybe the README of this project or the doc could mention that negative values are in fact correct and that the bounds are -1 and 1.

**Comment by jterrace** [comment]
@shanemcquillan - do you mind if we add the sample images in your post to the repo? Are they copyrighted?

**Comment by shanemcquillan** [comment]
Thanks for the clarification Wieland, that was very helpful. I'm interested in normalizing the score to a value between 0 and 1. Would adding 1 and diving by 2 make sense?

@jterrace I found this image here - http://www.imagemagick.org/Usage/compare/

ImageMagick is open source, so I'd imagine you're good.

**Comment by Alethiea-Cheng** [comment]
> Although unintuitive, values below 0 are in fact correct. The SSIM publications point out the unique maximum at 1 and skip over the part of a minimum value, so many people seem to just assume 0 (me included). It is only mentioned that the third term / the cross correlation can be negative.
> 
> [Structural Approaches to Image Quality Assessment](https://ece.uwaterloo.ca/~z70wang/publications/HIVP_chapter83.pdf) goes into most detail about this:
> 
> > Notice that s(x, y) can take on negative values. As will be shown in later examples, the negative structural similarity values correspond to the cases that the local image structures are inverted.
> 
> [Wikipedia](https://en.wikipedia.org/wiki/Structural_similarity) mentions the bounds correctly (-1 to 1), this [OpenCV example](http://docs.opencv.org/2.4/doc/tutorials/gpu/gpu-basics-similarity/gpu-basics-similarity.html) does not (zero to one).
> 
> It's easy to reproduce an ssim value close to -1:
> 
> ```
> from numpy.random import randint
> from PIL import Image
> random_img = randint(0, 255, (1000, 1000)).astype(np.uint8)
> print(compute_ssim(Image.fromarray(random_img), Image.fromarray(255 - random_img)))
> # -0.965838768437 for me
> ```
> 
> Maybe the README of this project or the doc could mention that negative values are in fact correct and that the bounds are -1 and 1.

Really a "seeking truth from facts" hero, bro (or sis)
