### ISSUE TITLE
How to use it in python source code

### ISSUE THREAD

**Issue by mothman1** [jterrace/pyssim#19]
I'm new to python and I would like to use pyssim in my code. I couldnt import pyssim as I get no module names pyssim, and I couldnt import ssim as I get no module named ssim.

Would you please tell me how to import pyssim and use it in my code?

**Comment by jterrace** [comment]
The module name is `ssim`. Did you install via pypi?

**Comment by mothman1** [comment]
Thanks, the lib was installed successfully. It was my fault, I wasn't importing it properly - I managed to start using it now
