### ISSUE TITLE
The results are different when used in a python file and used in command line

### ISSUE THREAD

**Issue by AllenIrving** [jterrace/pyssim#31]
Hi there. Thanks for the effort. I have one question using this module. When I used it in the command line where the command was `pyssim img1.png img2.png`, the result was, let's say 0.67, but when I tried to use the module in a python file, the result was different, it became something like 0.90. I was wondering if I was using it correctly. I write a function to wrap things up a little bit. The code goes below:
`import ssim`
`def compute_ssim(img1, img2):`
&emsp; &emsp;`s = ssim.SSIM(img1)`
&emsp;&emsp;`return s.cw_ssim_value(img2)`
Then when I need to compute the ssim value between two images I used the code`compute_ssim(img1, img2)` where `img1` and `img2` were obtained by  PIL.Image.open function. As I said above, the results were different. Was I using it wrong or something?

**Comment by jterrace** [comment]
`cw_ssim_value` is the CW-SSIM version. You want the regular `ssim_value` method for SSIM. Alternatively, pass the `--cw` flag to the command line tool.

**Comment by jterrace** [comment]
Please reopen if that doesn't fix it.
