### ISSUE TITLE
Imagens in sub directories

### ISSUE THREAD

**Issue by marcelovieiratecnologia** [jterrace/pyssim#35]
I need you to compare within sub directories too!
Do you have any idea how I can do it?

**Comment by jterrace** [comment]
I'm kind of confused what you're asking for. Can you give an example?

**Comment by marcelovieiratecnologia** [comment]
example:
I have images in a directory and sub directory
Structure of where my images are:

directory / images.jpg
               / directory1 / images.jpg
                                   /direction1.1/images.jpg
                                   /directory1.2/images.jpg
               / directory2 / images.jpg
                                   /directory2.1/images.jpg
                         
I have images in such a structure.

**Comment by jterrace** [comment]
Can't you do that with a bash script?

**Comment by marcelovieiratecnologia** [comment]
I already solved it

but still thank you so much!
