### ISSUE TITLE
Supporting Python 3.6

### ISSUE THREAD

**Issue by VladSha-Usa** [jterrace/pyssim#39]
Hello!
My app uses the pyssim module and Python 2.7. I need to port the app to Python 3.6.
I see Python 3.6 in .travis CI file. Does the module support this version?

**Comment by jterrace** [comment]
I just updated to github actions and it looks good:
https://github.com/jterrace/pyssim/actions/runs/2488788598

I dropped 2.7 and 3.6 since they're already end of life:
https://endoflife.date/python

Currently supporting 3.7, 3.8, 3.9, and 3.10.

Let me know if you need a package release on pypi.
