### ISSUE TITLE
Not compatible with numpy 1.20

### ISSUE THREAD

**Issue by labay11** [jterrace/pyssim#43]
In numpy 1.20 they remove the support for `numpy.float` which makes the code fail in several lines like: https://github.com/jterrace/pyssim/blob/9324d8dd41dccc2001bd6dc8d6c1ec7600b50814/ssim/utils.py#L40

The solution is simply replacing it by just `float`.

**Comment by labay11** [comment]
Hi @jterrace, thanks for merging. Would it be possible to have a version release soon?

**Comment by jterrace** [comment]
Sure, it'll have to be next week though. I'm on work travel at the moment. I will get back to you.

**Comment by jterrace** [comment]
Sorry for the delay, just published version 0.6
